markdown:         rdiscount
pygments:         true
paginate:         5

title:            Hello Javake
url:              http://javake.github.io
feed:             /atom.xml
author:
    name:         Javake
    email:        javake@outlook.com
    description:  "a coder, a power man."

about:            "Hi, I am Javake. I am a coder, i am expert in android, java, recently i fund git is so cool ..."
follow:
    email:        javake@outlook.com
    github:       https://github.com/javake
    twitter:      http://www.twitter.com/
    google:       https://plus.google.com/
    facebook:	  http://www.facebook.com/
description:      Hello github

indexContent:     true
imageLink:        /images/pen.jpg


style:            /css/style.css
blogName:         Javake 
blogDesc:         a lazy coder ~
favicon:          /favicon.ico
theme:            default

disqus:           javake

copyright:        Copyright © 2014-2015 Javake All rights reserved.
test:             ok
