markdown:         rdiscount
pygments:         true
paginate:         4

title:            Hello Javake
url:              http://javake.github.io
feed:             /atom.xml
author:
    name:         Javake
    email:        javake@outlook.com
    description:  "a coder, a power man."

about:            "I am Javake. I am a coder, i am expert in android, java ..."
follow:
    email:        javake@outlook.com
    github:       https://github.com/javake
    twitter:      http://www.twitter.com/
    google:       https://plus.google.com/
    facebook:	  http://www.facebook.com/
description:      Hello github

indexContent:     true
imageLink:        /images/juanshoutian.jpg


style:            /css/style.css
blogName:         Javake 
blogDesc:         Javake`s Blog
favicon:          /favicon.ico
theme:            default

disqus:           disqus_javake

copyright:        Copyright © 2011-2012 Javake All rights reserved.
test:             ok
